export type TargetLanguage = 'th' | 'en'

interface StorageReader {
  getItem(key: string): string | null
}

const thai: Record<string, string> = {
  'auth.title': 'เข้าสู่ระบบ',
  'auth.description': 'ใช้บัญชี Mango ของคุณเพื่อเปิดรายการอัปเดตโปรแกรม',
  'auth.formTitle': 'ข้อมูลเข้าสู่ระบบ',
  'auth.company': 'ชื่อบริษัท',
  'auth.companyLoading': 'กำลังโหลดรายชื่อบริษัท…',
  'auth.companySelect': 'เลือกบริษัท',
  'auth.companyLoadFailed': 'โหลดรายชื่อบริษัทไม่สำเร็จ สามารถกรอกรหัสบริษัทแทนได้',
  'auth.companyRetry': 'ลองอีกครั้ง',
  'auth.user': 'ชื่อผู้ใช้',
  'auth.password': 'รหัสผ่าน',
  'auth.submit': 'เข้าสู่ระบบ',
  'auth.submitting': 'กำลังเข้าสู่ระบบ…',
  'auth.failed': 'เข้าสู่ระบบไม่สำเร็จ',
  'auth.required': 'กรุณากรอกรหัสบริษัท ชื่อผู้ใช้ และรหัสผ่าน',
  'auth.unavailableTitle': 'ไม่สามารถเข้าสู่ระบบได้',
  'auth.unavailableMessage': 'บริการแบ็กเอนด์สำหรับเข้าสู่ระบบไม่พร้อมใช้งานในขณะนี้ กรุณาติดต่อผู้ดูแลระบบแล้วลองอีกครั้ง',
  'auth.backToManual': 'กลับไปหน้ารายการอัปเดต',
  'manual.title': 'รายการอัพเดทโปรแกรม',
  'manual.description': 'ค้นหาและเปิดดูรายละเอียดการอัปเดตแยกตามโมดูล',
  'manual.filters': 'ตัวกรองรายการ',
  'manual.dateMode': 'ค้นหาตามวันที่',
  'manual.revisionMode': 'ค้นหาตาม Revision',
  'manual.startDate': 'วันที่เริ่มต้น',
  'manual.endDate': 'วันที่สิ้นสุด',
  'manual.startRevision': 'Revision เริ่มต้น',
  'manual.endRevision': 'Revision สิ้นสุด',
  'manual.condition': 'เงื่อนไข',
  'manual.search': 'ค้นหา',
  'manual.between': 'ระหว่าง',
  'manual.moreThan': 'มากกว่า',
  'manual.lessThan': 'น้อยกว่า',
  'manual.equal': 'เท่ากับ',
  'manual.number': 'ลำดับ',
  'manual.revision': 'Revision No.',
  'manual.subject': 'หัวข้อ',
  'manual.date': 'วันที่',
  'manual.loading': 'กำลังโหลดรายการอัปเดต',
  'manual.authChecking': 'กำลังตรวจสอบสถานะการเข้าสู่ระบบ',
  'manual.authRequired': 'ต้องเข้าสู่ระบบ',
  'manual.authUnavailable': 'ไม่สามารถเปิดหน้าลงชื่อเข้าใช้ได้ในขณะนี้ เนื่องจากบริการแบ็กเอนด์ไม่พร้อมใช้งาน กรุณาติดต่อผู้ดูแลระบบแล้วลองอีกครั้ง',
  'manual.empty': 'ไม่พบรายการอัพเดทซอฟต์แวร์',
  'manual.error': 'ไม่สามารถโหลดรายการอัปเดตได้',
  'manual.retry': 'ลองอีกครั้ง',
  'manual.attachments': 'เอกสารแนบ',
  'manual.attachmentLoading': 'กำลังโหลดเอกสารแนบ',
  'manual.attachmentEmpty': 'ไม่พบเอกสารแนบ',
  'manual.attachmentError': 'ไม่สามารถโหลดเอกสารแนบได้',
  'manual.open': 'เปิดไฟล์',
  'manual.download': 'ดาวน์โหลด',
  'manual.close': 'ปิดหน้าต่าง',
  'qcItem.title': 'รายการ QC Item',
  'qcItem.description': 'ตั้งค่ารายการคำถามการประเมิน',
  'qcItem.count': 'จำนวนข้อมูลทั้งหมด',
  'qcItem.number': 'ลำดับ',
  'qcItem.action': 'ดำเนินการ',
  'qcItem.actions': 'การดำเนินการของ QCItem',
  'qcItem.descriptionColumn': 'Description',
  'qcItem.remark': 'Remark',
  'qcItem.addDate': 'วันที่เพิ่ม',
  'qcItem.add': 'เพิ่มรายการ',
  'qcItem.save': 'บันทึก',
  'qcItem.saving': 'กำลังบันทึก…',
  'qcItem.export': 'ส่งออก Excel',
  'qcItem.exporting': 'กำลังเตรียมไฟล์ส่งออก…',
  'qcItem.import': 'นำเข้า Excel',
  'qcItem.importTitle': 'นำเข้ารายการ QC Item',
  'qcItem.selectedFile': 'ไฟล์ที่เลือก',
  'qcItem.chooseFile': 'เลือกไฟล์ .xlsx',
  'qcItem.cancel': 'ยกเลิก',
  'qcItem.upload': 'อัปโหลด',
  'qcItem.uploading': 'กำลังอัปโหลด…',
  'qcItem.importHint': 'สามารถใช้ไฟล์ Excel ที่ส่งออกจากหน้านี้เพื่อนำเข้ากลับได้',
  'qcItem.loading': 'กำลังโหลดรายการ QC Item',
  'qcItem.empty': 'ไม่พบรายการ QC Item',
  'qcItem.error': 'ไม่สามารถโหลดรายการ QC Item ได้',
  'qcItem.invalidResponse': 'เซิร์ฟเวอร์ส่งข้อมูลรายการ QC Item ไม่ถูกต้อง',
  'qcItem.retry': 'ลองอีกครั้ง',
  'qcItem.validation': 'กรุณากรอกข้อมูลให้ครบถ้วน',
  'qcItem.descriptionRequired': 'กรุณากรอก Description',
  'qcItem.remarkRequired': 'กรุณากรอก Remark',
  'qcItem.deleteConfirm': 'คุณต้องการลบรายการนี้ใช่หรือไม่',
  'qcItem.deleteItem': 'ลบรายการ',
  'qcItem.saveSuccess': 'บันทึกสำเร็จ',
  'qcItem.importSuccess': 'นำเข้าสำเร็จ',
  'qcItem.exportError': 'ไม่สามารถส่งออกไฟล์ได้',
  'qcItem.fileTypeError': 'กรุณาเลือกไฟล์ .xlsx เท่านั้น',
  'qcItem.authChecking': 'กำลังตรวจสอบสถานะการเข้าสู่ระบบ',
  'qcItem.accessDeniedTitle': 'ไม่มีสิทธิ์เข้าถึง',
  'qcItem.accessDeniedMessage': 'คุณไม่มีสิทธิ์เข้าถึงรายการ QC Item',
  'qcItem.accessErrorTitle': 'ไม่สามารถตรวจสอบสิทธิ์เข้าถึง QC Item ได้',
  'qcItem.accessRetry': 'ตรวจสอบสิทธิ์อีกครั้ง',
  'qcItem.readOnly': 'ดูข้อมูลได้อย่างเดียว',
  'qcItem.authRequired': 'ต้องเข้าสู่ระบบ',
  'qcItem.authUnavailable': 'ไม่สามารถเปิดหน้าลงชื่อเข้าใช้ได้ในขณะนี้ กรุณาติดต่อผู้ดูแลระบบแล้วลองอีกครั้ง',
}

const english: Record<string, string> = {
  'auth.title': 'Sign in',
  'auth.description': 'Use your Mango account to open the program update list.',
  'auth.formTitle': 'Account details',
  'auth.company': 'Company',
  'auth.companyLoading': 'Loading companies…',
  'auth.companySelect': 'Select a company',
  'auth.companyLoadFailed': 'Could not load companies. Enter the company code instead.',
  'auth.companyRetry': 'Try again',
  'auth.user': 'User name',
  'auth.password': 'Password',
  'auth.submit': 'Sign in',
  'auth.submitting': 'Signing in…',
  'auth.failed': 'Sign-in failed',
  'auth.required': 'Enter your company code, user name, and password.',
  'auth.unavailableTitle': 'Sign-in unavailable',
  'auth.unavailableMessage': 'The backend sign-in service is currently unavailable. Contact your administrator, then try again.',
  'auth.backToManual': 'Return to program updates',
  'manual.title': 'Program update list',
  'manual.description': 'Search and review update details by module.',
  'manual.filters': 'List filters',
  'manual.dateMode': 'Search by date',
  'manual.revisionMode': 'Search by revision',
  'manual.startDate': 'Start date',
  'manual.endDate': 'End date',
  'manual.startRevision': 'Start revision',
  'manual.endRevision': 'End revision',
  'manual.condition': 'Condition',
  'manual.search': 'Search',
  'manual.between': 'Between',
  'manual.moreThan': 'Greater than',
  'manual.lessThan': 'Less than',
  'manual.equal': 'Equal to',
  'manual.number': '#',
  'manual.revision': 'Revision No.',
  'manual.subject': 'Subject',
  'manual.date': 'Date',
  'manual.loading': 'Loading program updates',
  'manual.authChecking': 'Checking your session',
  'manual.authRequired': 'Sign-in required',
  'manual.authUnavailable': 'The sign-in page is currently unavailable because the backend service is not running. Contact your administrator, then try again.',
  'manual.empty': 'No software updates found',
  'manual.error': 'Unable to load program updates',
  'manual.retry': 'Try again',
  'manual.attachments': 'Attachments',
  'manual.attachmentLoading': 'Loading attachments',
  'manual.attachmentEmpty': 'No attachments found',
  'manual.attachmentError': 'Unable to load attachments',
  'manual.open': 'Open file',
  'manual.download': 'Download',
  'manual.close': 'Close dialog',
  'qcItem.title': 'QC Item list',
  'qcItem.description': 'Configure evaluation question items.',
  'qcItem.count': 'Total records',
  'qcItem.number': 'No.',
  'qcItem.action': 'Action',
  'qcItem.actions': 'QCItem actions',
  'qcItem.descriptionColumn': 'Description',
  'qcItem.remark': 'Remark',
  'qcItem.addDate': 'Add date',
  'qcItem.add': 'Add item',
  'qcItem.save': 'Save',
  'qcItem.saving': 'Saving…',
  'qcItem.export': 'Export Excel',
  'qcItem.exporting': 'Preparing export…',
  'qcItem.import': 'Import Excel',
  'qcItem.importTitle': 'Import QC Items',
  'qcItem.selectedFile': 'Selected file',
  'qcItem.chooseFile': 'Choose an .xlsx file',
  'qcItem.cancel': 'Cancel',
  'qcItem.upload': 'Upload',
  'qcItem.uploading': 'Uploading…',
  'qcItem.importHint': 'The server-generated Excel export can be imported here for a round trip.',
  'qcItem.loading': 'Loading QC Items',
  'qcItem.empty': 'No QC Items found',
  'qcItem.error': 'Unable to load QC Items',
  'qcItem.invalidResponse': 'The server returned an invalid QC Item list.',
  'qcItem.retry': 'Try again',
  'qcItem.validation': 'Please complete all required fields.',
  'qcItem.descriptionRequired': 'Description is required.',
  'qcItem.remarkRequired': 'Remark is required.',
  'qcItem.deleteConfirm': 'Are you sure you want to delete this item?',
  'qcItem.deleteItem': 'Delete item',
  'qcItem.saveSuccess': 'Saved successfully.',
  'qcItem.importSuccess': 'Imported successfully.',
  'qcItem.exportError': 'Unable to export the file.',
  'qcItem.fileTypeError': 'Please choose an .xlsx file only.',
  'qcItem.authChecking': 'Checking your session',
  'qcItem.accessDeniedTitle': 'Access denied',
  'qcItem.accessDeniedMessage': 'You do not have access to QC Items.',
  'qcItem.accessErrorTitle': 'Unable to check QC Item access',
  'qcItem.accessRetry': 'Check access again',
  'qcItem.readOnly': 'Read only',
  'qcItem.authRequired': 'Sign-in required',
  'qcItem.authUnavailable': 'The sign-in page is currently unavailable. Contact your administrator, then try again.',
}

export interface LocalizationAdapter {
  language: TargetLanguage
  t(key: string): string
}

export function createLocalizationAdapter(storage: StorageReader): LocalizationAdapter {
  let preference: string | null = null
  try {
    preference = storage.getItem('user_lang')
  }
  catch {
    preference = null
  }

  const language: TargetLanguage = preference?.toUpperCase() === 'EN' ? 'en' : 'th'
  const dictionary = language === 'en' ? english : thai

  return {
    language,
    t(key) {
      return dictionary[key] ?? thai[key] ?? key
    },
  }
}
