import type { TargetLanguage } from '~/services/localization/localization-adapter'

/**
 * Slice-local dictionary for the mas001.* namespace. The shared localization
 * adapter is reused unchanged: the page prefers its `t()` and falls back to
 * these tables only when the adapter has no entry for the key.
 */
export const MAS001_TEXTS: Record<TargetLanguage, Record<string, string>> = {
  th: {
    'mas001.title': 'กลุ่มงานประกัน',
    'mas001.description': 'ตั้งค่ากลุ่มงานประกัน',
    'mas001.count': 'จำนวนข้อมูลทั้งหมด',
    'mas001.number': 'ลำดับ',
    'mas001.codeColumn': 'Group Code',
    'mas001.nameColumn': 'Group Name',
    'mas001.activeColumn': 'Active',
    'mas001.yes': 'Yes',
    'mas001.no': 'No',
    'mas001.searchBy': 'Search By',
    'mas001.searchFieldCode': 'Group Code',
    'mas001.searchFieldName': 'Group Name',
    'mas001.search': 'ค้นหา',
    'mas001.activeFilter': 'Active',
    'mas001.first': 'หน้าแรก',
    'mas001.prev': 'ก่อนหน้า',
    'mas001.next': 'ถัดไป',
    'mas001.last': 'หน้าสุดท้าย',
    'mas001.add': 'เพิ่มกลุ่ม',
    'mas001.edit': 'แก้ไข',
    'mas001.delete': 'ลบ',
    'mas001.defaultColumn': 'Default',
    'mas001.deleteConfirm': 'ต้องการลบ group code นี้',
    'mas001.deleteSuccess': 'ลบข้อมูลเรียบร้อยแล้ว',
    'mas001.addTitle': 'เพิ่ม Group Code',
    'mas001.editTitle': 'แก้ไข Group Code',
    'mas001.save': 'บันทึก',
    'mas001.saving': 'กำลังบันทึก…',
    'mas001.cancel': 'ยกเลิก',
    'mas001.codeInvalid': 'Group Code ต้องมีความยาว 1–20 ตัวอักษร A–Z, 0–9, ขีดกลาง หรือขีดล่างเท่านั้น',
    'mas001.nameInvalid': 'กรุณาระบุ Group Name (ไม่เกิน 200 ตัวอักษร)',
    'mas001.activeInvalid': 'Active ต้องเป็น Y หรือ N เท่านั้น',
    'mas001.saveSuccess': 'บันทึกข้อมูลเรียบร้อยแล้ว',
    'mas001.authChecking': 'กำลังตรวจสอบสถานะการเข้าสู่ระบบ',
    'mas001.authRequired': 'ต้องเข้าสู่ระบบ',
    'mas001.authUnavailable': 'ไม่สามารถเปิดหน้าลงชื่อเข้าใช้ได้ในขณะนี้ กรุณาติดต่อผู้ดูแลระบบแล้วลองอีกครั้ง',
    'mas001.accessDeniedTitle': 'ไม่มีสิทธิ์เข้าถึง',
    'mas001.accessDeniedMessage': 'คุณไม่มีสิทธิ์เข้าถึงกลุ่มงานประกัน',
    'mas001.accessErrorTitle': 'ไม่สามารถตรวจสอบสิทธิ์เข้าถึงกลุ่มงานประกันได้',
    'mas001.accessRetry': 'ตรวจสอบสิทธิ์อีกครั้ง',
    'mas001.readOnly': 'ดูข้อมูลได้อย่างเดียว',
    'mas001.loading': 'กำลังโหลดกลุ่มงานประกัน',
    'mas001.empty': 'ไม่พบกลุ่มงานประกัน',
    'mas001.error': 'ไม่สามารถโหลดกลุ่มงานประกันได้',
    'mas001.invalidResponse': 'เซิร์ฟเวอร์ส่งข้อมูลกลุ่มงานประกันไม่ถูกต้อง',
    'mas001.retry': 'ลองอีกครั้ง',
    'mas001.import': 'นำเข้า',
    'mas001.importTitle': 'นำเข้า Group Code',
    'mas001.importMapCode': 'คอลัมน์ Code',
    'mas001.importMapName': 'คอลัมน์ Name',
    'mas001.importMapActive': 'คอลัมน์ Active',
    'mas001.importPaste': 'แถวจากสเปรดชีต',
    'mas001.importPreview': 'ตัวอย่างก่อนนำเข้า',
    'mas001.importUpload': 'อัปโหลด',
    'mas001.importCancel': 'ยกเลิก',
    'mas001.importSuccess': 'นำเข้าข้อมูลเรียบร้อยแล้ว',
    'mas001.importEmpty': 'ไม่มีข้อมูลให้นำเข้า — วางแถวแล้วจับคู่คอลัมน์',
    'mas001.export': 'ส่งออก Excel',
    'mas001.exporting': 'กำลังเตรียมไฟล์ส่งออก…',
    'mas001.template': 'ดาวน์โหลดเทมเพลต',
    'mas001.templateDownloading': 'กำลังเตรียมเทมเพลต…',
    'mas001.exportBlocked': 'ไม่สามารถเปิดหน้าต่างดาวน์โหลดได้ (ป๊อปอัพถูกบล็อก) กรุณาอนุญาตป๊อปอัพแล้วลองอีกครั้ง',
    'mas001.exportFailed': 'ไม่สามารถเตรียมไฟล์สำหรับดาวน์โหลดได้',
  },
  en: {
    'mas001.title': 'Warranty Group list',
    'mas001.description': 'Configure warranty work groups.',
    'mas001.count': 'Total records',
    'mas001.number': 'No.',
    'mas001.codeColumn': 'Group Code',
    'mas001.nameColumn': 'Group Name',
    'mas001.activeColumn': 'Active',
    'mas001.yes': 'Yes',
    'mas001.no': 'No',
    'mas001.searchBy': 'Search By',
    'mas001.searchFieldCode': 'Group Code',
    'mas001.searchFieldName': 'Group Name',
    'mas001.search': 'Search',
    'mas001.activeFilter': 'Active',
    'mas001.first': 'First',
    'mas001.prev': 'Prev',
    'mas001.next': 'Next',
    'mas001.last': 'Last',
    'mas001.add': 'Add group',
    'mas001.edit': 'Edit',
    'mas001.delete': 'Delete',
    'mas001.defaultColumn': 'Default',
    'mas001.deleteConfirm': 'Do you want to delete this group code',
    'mas001.deleteSuccess': 'Group deleted successfully.',
    'mas001.addTitle': 'Add Group Code',
    'mas001.editTitle': 'Edit Group Code',
    'mas001.save': 'Save',
    'mas001.saving': 'Saving…',
    'mas001.cancel': 'Cancel',
    'mas001.codeInvalid': 'Group Code must be 1-20 characters: A-Z, 0-9, dash, underscore.',
    'mas001.nameInvalid': 'Group Name is required (max 200 characters).',
    'mas001.activeInvalid': 'Active must be Y or N.',
    'mas001.saveSuccess': 'Your information has been saved successfully.',
    'mas001.authChecking': 'Checking your session',
    'mas001.authRequired': 'Sign-in required',
    'mas001.authUnavailable': 'The sign-in page is currently unavailable. Contact your administrator, then try again.',
    'mas001.accessDeniedTitle': 'Access denied',
    'mas001.accessDeniedMessage': 'You do not have access to Warranty Groups.',
    'mas001.accessErrorTitle': 'Unable to check Warranty Group access',
    'mas001.accessRetry': 'Check access again',
    'mas001.readOnly': 'Read only',
    'mas001.loading': 'Loading Warranty Groups',
    'mas001.empty': 'No Warranty Groups found',
    'mas001.error': 'Unable to load Warranty Groups',
    'mas001.invalidResponse': 'The server returned an invalid Warranty Group list.',
    'mas001.retry': 'Try again',
    'mas001.import': 'Import',
    'mas001.importTitle': 'Import Group Codes',
    'mas001.importMapCode': 'Code column',
    'mas001.importMapName': 'Name column',
    'mas001.importMapActive': 'Active column',
    'mas001.importPaste': 'Spreadsheet rows',
    'mas001.importPreview': 'Preview',
    'mas001.importUpload': 'Upload',
    'mas001.importCancel': 'Cancel',
    'mas001.importSuccess': 'Import completed successfully.',
    'mas001.importEmpty': 'Nothing to import — paste rows and map the columns.',
    'mas001.export': 'Export Excel',
    'mas001.exporting': 'Preparing export…',
    'mas001.template': 'Download template',
    'mas001.templateDownloading': 'Preparing template…',
    'mas001.exportBlocked': 'The download popup was blocked. Allow popups, then try again.',
    'mas001.exportFailed': 'Unable to prepare the file for download.',
  },
}
